server:
  # 端口号
  port: 8080
  # 项目路径
  context-path: /springboot
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-test
    username: root
    password: 123456
    
    # Druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化
    initialSize: 3
    # 最大
    maxActive: 20
    # 最小
    minIdle: 3
    # 最大连接等待超时时间
    maxWait: 60000
    # 打开PSCache,并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false 
    # 配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间,单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
# mybatis配置
#mybatis:
#  config-locations: classpath*:mybatis/mybatis-config.xml
#  mapper-locations: classpath*:mybatis/mapper/*.xml
#  type-aliases-package: com.springboot.entity
# 开启驼峰功能这里不开启,这里因为使用xml,所以在xml中使用
#mybatis:
#  configuration:
#    mapUnderscoreToCamelCase: true
# 日志
logging:
  level:
    # 设置包的日志输出级别(开发建议使用debug)
    com.cn.family: debug