# tomcat配置
server:
  # 端口号
  port: 7070
  # 项目路径
  servlet:
    context-path: /myfamliy

spring:
  profiles:
    active: dev
    # 多环境打包开启下面的配置,并使用clean package clean package -P dev/prod/test运行
    # active: @profileActive@

  # Spring Boot默认的提供的静态文件配置路径位于src/main/resources下,目录名称需要符合以下规定：
  # /static
  # /public
  # /resources
  # /META-INF/resources
  
  # 日期转化,springboot默认使用jackjson,另一种方式是使用alibaba的fastjson的注解
  # @JSONField(format = "yyyy-MM-dd HH:mm:ss")加config配置
  # 或者使用下面jackson配置
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

  # html视图
  mvc:
    view:
      prefix: /view/
      suffix: .html
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# mybatis配置
mybatis:
  ## 设置整个包下类的别名,或者使用mybatis-config.xml设置(一样的效果)
  ## 表示扫描该包名下的所有类(除了接口和匿名内部类),如果类名上有注解,则使用注解指定的名称作为别名,如果没有则使用类名首字母小写作为别名
  #
  ## typeAliasesPackage: com.hkb.springboot.dto, com.hkb.springboot.entity
  ## 配置mapper的扫描，找到所有的mapper.xml映射文件
  ##  mapperLocations: classpath:mybatis/mapper/*.xml
  # 等同与上面
#  type-aliases-package: com.hkb.springboot.dto, com.hkb.springboot.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# 开启驼峰功能这里不开启,这里因为使用xml,所以在mybatis-config.xml中使用
#  configuration:
#    mapUnderscoreToCamelCase: true
# pagehelper分页助手-另一种方式在代码里配置 
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
